### ISSUE TITLE
import firmy přes ARES & vytvoření - 403 Forbidden

### ISSUE THREAD

**Issue by axo4xo** [pslib-cz/pslib-internship-g4#1]
![image](https://github.com/user-attachments/assets/2a62377d-9c69-4ff4-aa11-be7b3db6797f)
![image](https://github.com/user-attachments/assets/f4cafa24-b4c1-421b-8f42-09245a6d057e)

**Comment by MichalStehlik** [comment]
Tohle je příliš přísné: https://github.com/pslib-cz/pslib-internship-g4/blob/b5afd3e9919516aec98ba975afa86ff1e3d9c172/src/app/api/locations/route.ts#L120

Bude opraveno v další verzi.
