### ISSUE TITLE
/companies API endpoint - 403 Forbidden

### ISSUE THREAD

**Issue by axo4xo** [pslib-cz/pslib-internship-g4#2]
Uživatel nemá oprávnění přidat firmu

https://github.com/pslib-cz/pslib-internship-g4/blob/b5afd3e9919516aec98ba975afa86ff1e3d9c172/src/app/api/companies/route.ts#L109

![image](https://github.com/user-attachments/assets/1dc5ead0-1841-4c94-a613-8dce23fc0ca8)

**Comment by MichalStehlik** [comment]
fixed + deployed

https://github.com/pslib-cz/pslib-internship-g4/blob/cd5e83f0a49d77fd72c4e76ca529d2052b2fb9fc/src/app/api/companies/route.ts#L110
