### ISSUE TITLE
POST /api/interships - 403 Forbidden

### ISSUE THREAD

**Issue by axo4xo** [pslib-cz/pslib-internship-g4#3]
uživatel nemůže založit praxi

https://github.com/pslib-cz/pslib-internship-g4/blob/fec30466dc0db902794a21e1def5315a593e67bd/src/app/api/internships/route.ts#L252

<img width="440" alt="image" src="https://github.com/user-attachments/assets/cf0a3249-3877-4806-b2ce-b530fb3df48d">

**Comment by MichalStehlik** [comment]
Tak, jak je to napsané, musí být součástí požadavku i id toho, kdo na té praxi bude. Což nebylo.
https://github.com/pslib-cz/pslib-internship-g4/blob/6a876c81713181f9e5d267f11b1c67c10071cb89/src/app/(front)/internships/create/CreateInternshipForm.tsx#L160
